version: '2'

services:
  db:
    container_name: bftp_db
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE = ./secrets/mysql-root-password
      - MYSQL_DATABASE_FILE = ./secrets/mysql-db
      - MYQSL_USER_FILE = ./secrets/mysql-user
      - MYSQL_PASSWORD_FILE = ./secrets/mysql-password
    ports:
      - "3306:3306"

  worker:
    image: python:latest
    container_name: bftp_w1
    links:
      - db
    volumes:
      - ./worker:/opt/bftp/worker