version: '3.1'

services:
  db:
    container_name: bftp_db
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE = ./secrets/mysql-root-password
      - MYSQL_DATABASE_FILE = ./secrets/mysql-db
      - MYQSL_USER_FILE = ./secrets/mysql-user
      - MYSQL_PASSWORD_FILE = ./secrets/mysql-password
    ports:
      - "3306:3306"

  web:
    container_name: bftp_web
    build: web
    links:
      - db
    volumes:
      - ./images:/var/bftp/images/
      - ./hashes:/var/bftp/hashes/
      - H:\My Documents\My Pictures:/var/bftp/images/local
      - C:\Users\jonathan.martens\Dropbox\Camera Uploads:/var/bftp/images/dropbox
    environment:
      - MYSQL_DATABASE=bftp
      - MYSQL_USER=bftp
      - MYSQL_PASSWORD=bftp
    ports:
      - "8000:8000"

  worker:
    container_name: bftp_w1
    build: worker
    links:
      - db
    volumes:
