version: '3.1'

services:
  db:
    container_name: bftp_db
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE = ./secrets/mysql-root-password
      - MYSQL_DATABASE_FILE = ./secrets/mysql-db
      - MYQSL_USER_FILE = ./secrets/mysql-user
      - MYSQL_PASSWORD_FILE = ./secrets/mysql-password
    ports:
      - "3306:3306"

  web:
    container_name: bftp_web
    build: web

  web-new:
    container_name: btp_web_new
    build:
      context: https://github.com/jmartens/alpine-flask.git#patch-1
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bftp
      - MYSQL_USER=bftp
      - MYSQL_PASSWORD=bftp
    ports:
      - "8080:80"
    volumes:
      # Mount apps root folder as a volume for convenience and quick reload
      - ./web2:/app
      # Mount storage of hashes as a volume
      - ./hashes:/app/app/static/images/hashes/
      # Mount image folders as volumes
      - ./images:/app/app/static/images

  worker:
    container_name: bftp_w1
    build: worker
    links:
      - db
    volumes:
